### ISSUE TITLE
missing templates for linux/os x command line operation

### ISSUE THREAD

**Issue by mp15** [DKMS-LSL/typeloader#1]
Hi, could you create some examples of the config_base.ini and config_company.ini files for linux installs please?

**Comment by mp15** [comment]
Also seem to be missing template for tables too

**Comment by vineeth-s** [comment]
@mp15 config_base.ini and config_company.ini are now in the src directory

**Comment by bmschoene** [comment]
TypeLoader is not meant for command line, but the new release 2.1.0 comes with a Setup Linux page that explains (among other things) how to create the config files: http://srvddgit01.labor.local/bioinf/applications/typeloader/typeloader2/blob/master/user_manual/setup_linux.md
