### ISSUE TITLE
feature numbering in feature table

### ISSUE THREAD

**Issue by droe-nmdp** [DKMS-LSL/typeloader#10]
The feature (intron/exon) numbering in the feature table skips numbers due to multi-gene homology wherein some exons of some genes are pseudo exons. 

Was this suggested by ENA or was that a decision based on IPD-KIR direction/considerations? The DDBJ/ENA/GenBank documentation doesn't seem clear to me.

**Comment by bmschoene** [comment]
This should only apply to genes which have psuedoexons, I think.... TypeLoader uses the numbering as requested by ENA and IPD in the appropriate files.

Which gene are you looking at?

**Comment by droe-nmdp** [comment]
Yes, all genes with psuedoexons. If you are confirming that ENA wants exon numbers to be skipped for pseudoexons, that answers my question. I can't find any ENA/DDBJ/GenBank documentation of the subject.

**Comment by bmschoene** [comment]
It appears the current IPD-KIR release is broken, which may be the reason you experience this. Sorry! :(

We haven't really found a way yet to check new IPD files for such things, as they always break in unexpeted places when they do, and often without even the warning of a version bump. I suggest you hold off from using TypeLoader until the next time you get an "I have found a new KIR version!" popup after login...

(I will try to get a way to at least manually use a specific non-broken release version into the new release, but I can't promise.)

**Comment by droe-nmdp** [comment]
Thank you.
