### ISSUE TITLE
ENA submission error / SOLUTION ( I think )

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#13]
During an ENA submission, TypeLoader replied as below:
=======================================
ERROR: ENA rejected your files (validation failed):

ERROR: Your application version is no longer supported. The minimum supported version is 2.0.0. Please download the latest version 2.2.0 from https://github.com/enasequence/webin-cli/releases

The complete submission has been rejected.
=======================================

Trying to solve the problem, I followed the error message recommendation;

1) Access https://github.com/enasequence/webin-cli/releases
2) Download webin-cli-2.2.0.jar
3) Replace the old version by the downloaded one at:
C:\Program Files (x86)\TypeLoader\ENA_Webin_CLI
   - Remove webin-cli-1.8.4.jar
   - Paste webin-cli-2.2.0.jar

It worked !!!   : )

**Comment by bmschoene** [comment]
Well done! :-)

I know about this issue - the new Webin CLI version was announced late last year - but I haven't had the opportunity to ship a new TypeLoader version including the new CLI.

The upcoming release will, of course, contain the new webin CLI version. Until then, what you did was exactly right. :-)
