### ISSUE TITLE
setup.exe missing

### ISSUE THREAD

**Issue by vineeth-s** [DKMS-LSL/typeloader#2]
> Hi Vineeth,
> 
> This is Elaine from the HLA lab at St. Jude Children’s Hospital. We’ve exchanged emails regarding the Typeloader software last year.
> I saw that your group has an abstract in this year’s ASHI about a Window version of Typeloader and we’re really interested in giving it a try.
> However, from the GitHub Typeloader website, I could not figure out where I can find the Setup_TypeLoader.exe file to install the software. 
> Could you please point me to the right direction where I can download the software?
> 
> Thank you so much,
> Elaine
>

**Comment by bmschoene** [comment]
Release 2.1.0 contains the (updated) installer.
