### ISSUE TITLE
Windows Installer for 2.8.2.1 is broken for first installs

### ISSUE THREAD

**Issue by bmschoene** [DKMS-LSL/typeloader#20]
@stephencheunghk posted in #5:

> Hello,
> I got an error message when I open the 2.8.2.1 software after installation on a windows 10 workstation.
> Please advise if there is solution to it?
> 
> Thanks!
> 
> ![Typeloader_error](https://user-images.githubusercontent.com/83048196/115805442-92430180-a417-11eb-9d08-8d2496c30f39.png)

**Comment by bmschoene** [comment]
Oh, darn. It looks like the current installer does not correctly create the config files in which TypeLoader is supposed to store the things you enter during setup. So the installer works fine to update existing installations, but it cannot be used to create a new installation. :(

@stephencheunghk I will have to fix this in the next release, but it might take a while, since I'm surrently busy with other stuff.
Meanwhile, you could probably install one of the older versions, see if you can open these, and if yes, use the installer of the 2.8.2.1 version to update (choose "update an existing TypeLoader installation?" => "yes" during installation of the 2.8.2.1 version). That should hopefully work until I get to finishing the new release.

I'm very sorry for the inconvenience!

Please let me know whether this approach works out for you.

**Comment by stephencheunghk** [comment]
I found that the installer works if I choose "No" in "update an existing TypeLoader installation?". This will works as a new installation.

Will explore the functions and hopefully it can save my life. Many thanks for developing such a great submission tool!

**Comment by bmschoene** [comment]
@stephencheunghk Chosing "No" in "update an existing TypeLoader installation?" is the correct way to get a new installation, yes. :-)

I'm glad you got it to work. Enjoy TypeLoader, and I hope it helps you as it helps us. :-)

**Comment by stephencheunghk** [comment]
Not sure if this is related to the installation problem.
Another error was found about updating the HLA/KIR reference when the TypeLoader starts up. 
I have tried updating it multiple times but still fail. And it shows "The generated blast.xml file was empty. This was probably a BLAST hickup. Please restart TypeLoader and try again." when I try to add a new sequence to a project.

There is a line with incorrect path which may be the cause of the error? 
"File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_core\update_reference.py", line 82, in make_blast_db"

I copy part of the Iog here:
INFO [2021-04-26 14:24:13] - Checking HLA for IPD update...
INFO [2021-04-26 14:24:13] - => No local reference file found
INFO [2021-04-26 14:24:13] - => Found new reference version for hla
INFO [2021-04-26 14:24:13] - Checking KIR for IPD update...
INFO [2021-04-26 14:24:13] - => No local reference file found
INFO [2021-04-26 14:24:13] - => Found new reference version for kir
INFO [2021-04-26 14:24:15] - Retrieving new database version for hla...
DEBUG [2021-04-26 14:24:15] - 	downloading new file from https://github.com/DKMS-LSL/IMGTHLA/raw/Latest/hla.dat...
DEBUG [2021-04-26 14:28:17] - 	 => successfully downloaded new hla file
DEBUG [2021-04-26 14:28:17] - 	Creating parsed files...
DEBUG [2021-04-26 14:28:17] - 		Reading alleles from E:\Typeloader\_general\reference_data\temp\hla.dat...
DEBUG [2021-04-26 14:28:28] - 			=> found 29217 alleles
DEBUG [2021-04-26 14:28:28] - 		Writing E:\Typeloader\_general\reference_data\temp\parsedhla.fa...
DEBUG [2021-04-26 14:28:29] - 		Writing E:\Typeloader\_general\reference_data\temp\parsedhla.dump...
DEBUG [2021-04-26 14:28:30] - 		Writing E:\Typeloader\_general\reference_data\temp\hla_allelenames.dump...
DEBUG [2021-04-26 14:28:30] - 		Writing E:\Typeloader\_general\reference_data\temp\curr_version_hla.txt...
DEBUG [2021-04-26 14:28:30] - 	Creating local blast database...
ERROR [2021-04-26 14:28:30] - Command '['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Typeloader\\_general\\reference_data\\temp\\parsedhla.fa']' returned non-zero exit status 1.
Traceback (most recent call last):
  **File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_core\update_reference.py", line 82, in make_blast_db**
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Typeloader\\_general\\reference_data\\temp\\parsedhla.fa']' returned non-zero exit status 1.
DEBUG [2021-04-26 14:28:30] - C:\Program Files (x86)\TypeLoader\blastn\makeblastdb -dbtype nucl -in E:\Typeloader\_general\reference_data\temp\parsedhla.fa
ERROR [2021-04-26 14:28:30] - Could not create local blast database:
CalledProcessError(1, ['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Typeloader\\_general\\reference_data\\temp\\parsedhla.fa'])
C:\Program Files (x86)\TypeLoader\blastn\makeblastdb -dbtype nucl -in E:\Typeloader\_general\reference_data\temp\parsedhla.fa
INFO [2021-04-26 14:28:30] - Tried to update the reference data for HLA to version 3.43, but could not process it (see below). We'll continue to use the old files for now.

Could not create local blast database:
CalledProcessError(1, ['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Typeloader\\_general\\reference_data\\temp\\parsedhla.fa'])
C:\Program Files (x86)\TypeLoader\blastn\makeblastdb -dbtype nucl -in E:\Typeloader\_general\reference_data\temp\parsedhla.fa

**Comment by bmschoene** [comment]
Yeah, that probably is related. What you did by telling the installer you were updating an existing installation is you created a TypeLoader installation without config files, and now it's all distorted. The writing of these config files is what's broken in the current installer, but TypeLoader needs these config files. I'm surprised it worked at all...

I would advise to do the following:
- go to C:\Program Files (x86)\TypeLoader and execute the unstall.exe to uninstall TypeLoader completely
- download an older TypeLoader installer and use it to create a fresh installation (choose "No" whan asked if you want to update an existing version", then enter all the data it asks you, especially the path where TypeLoader should store its data - everything else can be changed later, but this path is crucial). I just checked, the 2.8.0 installer seems to work fine. This way, you get your config files.
- after this installation, execute the current (2.8.2.1) installer again to update it, this time chosing "Yes" when asked if you want to update an existing version (because that's exactly what you'll be doing). 

This way, you should end up with a working TypeLoader installation.

Again, sorry for the hassle. :( I'll fix it in the next release, but I really don't have the time to do a proper release within the next month or 2, and I don't think you'll want to wait that long.

**Comment by stephencheunghk** [comment]
Unfortunately, 2.8.0 installation followed by 2.8.2.1 doesn't work.
Same error message appears when updating reference data :(
I would like clarify that the error message "The generated blast.xml file was empty. This was probably a BLAST hickup. Please restart TypeLoader and try again." appears only after I moved the reference files from the "temp" folder to one directory up, i.e. the "reference_data" folder. 
The original error message should be something like the reference files do not exit in the "\....\reference_data" path and it may be a Wrong allele (can't recall the exact message). That's why I tried to move the reference files and resulted in another error message. 
Hope this information help.

Please dun worry and take your time :)
I will handle submission manually at the moment and look forward to your next release.

**Comment by bmschoene** [comment]
Manually moving the reference files is a bad idea. Generally, TypeLoader really doesn't like people touching its files except from within the TypeLoader GUI. This is intentional, to prevent users from accidentally breaking things.

Were you able to start TypeLoader after the 2.8.0 installation, and to create a test user? Did you delete the TypeLoader data path folder before attempting the installation of 2.8.0? 

I'm not sure which temp folder you mean? The folder that you name as TypeLoader's data path during installation should not be a temp folder, it should be the path where you want TypeLoader to write and keep all its data in the future: 
![image](https://user-images.githubusercontent.com/43027482/116211499-2b3d8980-a744-11eb-8922-48bf6a6cac95.png)
The data needs to stay there. Otherwise, TypeLoader will not be able to find it anymore. So choose a sensible directory.

After installation of 2.8.0, you can check the config files under `C:\Program Files (x86)\TypeLoader`:
- Among many other files, there should be a text file called `config_base.ini` that has the following content:
```
[Paths]
root_path: C:\Daten\TypeLoader
blast_path: C:\Program Files (x86)\TypeLoader\blastn\blastn
```
(Under "root path", it should contain the data path that you entered in the section shown in the screenshot above.)
- There should also be a text file called `config_company.ini` that has the following content:
```
[Company]
xml_center_name: 
ftp_user: 
ftp_pwd: 
proxy: 
cell_line_token: 
lab_of_origin: 
lab_contact: 
lab_contact_address: 
lab_contact_email: 
submittor_id: 
ipd_shortname: 
ipd_submission_length: 7
last_tl_version: 2.8.0
```
This should contain all the data you entered for your ENA and IPD connections.

Everything in the `config_company.ini` file can later be set for each individual user via the TypeLoader GUI, so don't fiddle with this file. It just needs to be there and contain all these lines.

For me, the 2.8.0 installer creates these files correctly, while the 2.8.2.1 installer does not.
Can you please verify whether you have these files, and that `root_path` in `config_base.ini` points to a directory that, after installation, should contain only a folder named `_general`, which in turn contains an empty folder called `sample_files`.

If that is the case, start TypeLoader. It will probably give this error: 
![image](https://user-images.githubusercontent.com/43027482/116213755-57f2a080-a746-11eb-90ef-359fec041bcf.png)
You can ignore that, just click "OK".

Then you should be able to create a test user.
And then it should ask you to update the database. (All of this is from 2.8.0.)

When that has gone through successfully, *then* I would close TypeLoader and use the 2.8.2.1 installer to update it.
This works on my machine, at least.

Can you try that procedure again, and let me know if and exactly where errors still occur?

**Comment by stephencheunghk** [comment]
I deleted all files in Program files (x86) and the data path before I do a clean installation of 2.8.0
I chose "No" when it prompted up for asking whether update an existing version, and entered the data path. However, error message appeared and failed to get into Typeloader GUI. (Same error message as in clean installation of 2.8.2.1 if I chose "Yes" for updating)
![Typeloader_error_2 8 0](https://user-images.githubusercontent.com/83048196/116232681-09b4c000-a78d-11eb-9d57-9afb65c3d376.png)
It can only get into the Typeloader GUI and create a test account after updating with 2.8.2.1 installer with "Yes" for updating an existing version (Or choose "No" when doing a clean install of 2.8.2.1). 
Anyway, all installation methods cannot update the HLA and KIR reference files. 
![Typeloader_error_reference files_2](https://user-images.githubusercontent.com/83048196/116236580-cf015680-a791-11eb-8784-cd4b897e7732.png)

Actually, I can see the reference data files were downloaded to the ".\_general\reference_data\temp\" folder
![Typeloader_error_reference files](https://user-images.githubusercontent.com/83048196/116234624-6add9300-a78f-11eb-8d55-0ac123cbb85d.png)

I didn't touch the config.ini files in the program files.
The files I moved was the reference data files in the data path
From ".\_general\reference_data\temp\" to ".\_general\reference_data\"
The reason was that I saw an error message saying the reference data do not exist in the ".\_general\reference_data\" path, when I was adding an alleles. Sorry for the unclear info in last reply.
![Typeloader_error_reference files_3](https://user-images.githubusercontent.com/83048196/116237700-248a3300-a793-11eb-8717-dad9fd081e1c.png)
After moving the files, it allowed me to enter further info
![Typeloader_error_reference files_4](https://user-images.githubusercontent.com/83048196/116238186-a67a5c00-a793-11eb-8236-c3ce74650f81.png)
But end up with another error
![Typeloader_error_reference files_5](https://user-images.githubusercontent.com/83048196/116238324-ca3da200-a793-11eb-84b0-efa203d011ce.png)

**Comment by bmschoene** [comment]
Ah, I see. Maybe we can fix this manually. (Close TypeLoader before attempting this.)

## Step 1: check or create your main config files

Can you check in `C:\Program Files (x86)\TypeLoader` whether the file `config_base.ini` is present?

If yes, open it in a text editor and make sure it contains the following content and nothing more:
```
[Paths]
root_path: E:\Novel alleles\TypeLoader
blast_path: C:\Program Files (x86)\TypeLoader\blastn\blastn
```
If it does not exist, create an empty text file there, paste this content into it, and rename it to `config_base.ini`. You will need admin privileges for this; depending on your computer's setup, you may have to create the file elsewhere and then move it into the target folder.

Do the same with the `config_company.ini` file explained in my previous comment. (Just use the text as it is.)

## Step 2: adjust your user config

Then you need to update the user config file of the user you created. You will find this under `E:\Novel alleles\TypeLoader\username\config.ini` (adjust the username for whatever you used to create your user, hopefully a test account. If you have created multiple users, you will need to do this for each of them).

Open this file in a text editor and scroll down to the section that starts with `[Path]`.

Replace the section with the following:
```
[Paths]
raw_files_path = 
default_saving_dir = 
root_path = E:\Novel alleles\TypeLoader
blast_path = C:\Program Files (x86)\TypeLoader\blastn\blastn
login_dir = E:\Novel alleles\TypeLoader\test
projects_dir = E:\Novel alleles\TypeLoader\test\projects
temp_dir = E:\Novel alleles\TypeLoader\test\temp
recovery_dir = E:\Novel alleles\TypeLoader\test\recovery
db_file = E:\Novel alleles\TypeLoader\test\data.db
dat_path = E:\Novel alleles\TypeLoader
```
Then save the file.

Then restart TypeLoader and see if it works. *fingers crossed*

**Comment by stephencheunghk** [comment]
The config.ini files are all present in both C:\program files (x86) and the root path.

Unfortunately, the same error message still appears when trying to update the reference data.
No matter I copy the content you provided or using the default one or not. 
![Typeloader_error_reference files_6](https://user-images.githubusercontent.com/83048196/116333282-c480a480-a805-11eb-9f1f-2e3d2b3f9c3d.png)
![Typeloader_error_reference files_7](https://user-images.githubusercontent.com/83048196/116333453-0873a980-a806-11eb-91c8-e2dcd646c63a.png)

Sigh

I got one question for this path
"blast_path = C:\Program Files (x86)\TypeLoader\blastn\blastn"
I find the directory for blastn as "C:\Program Files (x86)\TypeLoader\blastn", wonder why there is one more "blastn" in the path?

Thanks!

**Comment by bmschoene** [comment]
The first "blastn" points to the directory `blastn`, the second to the `blastn.exe` file within it.

*sigh* This is weird, but I don't see anything else we can try. :-(

I'm very sorry for all the hassle. I'll let you know when the new release is out. I'll make sure to test it thoroughly before uploading.

**Comment by bmschoene** [comment]
@stephencheunghk The new TypeLoader release 2.11.0 is finally here! You can find it here: https://github.com/DKMS-LSL/typeloader/releases/tag/V2.11.0

I have tested it (hopefully) thoroughly and it should work for fresh installations as well as updates to existing installations.

I'm very sorry you had to wait this long. I hope, TypeLoader can now finally help you with your novel alleles.

**Comment by stephencheunghk** [comment]
@bmschoene Thanks for the new release!
The installation works and I have done a clean installation.
However, similar error appear again when creating reference files(as attached below)
![image](https://user-images.githubusercontent.com/83048196/141244936-ee0ae54a-927a-412c-aae2-a7afaf12becb.png)

Log message is also attached for your information.

INFO [2021-11-11 13:32:28] - Checking HLA for IPD update...
INFO [2021-11-11 13:32:28] - => No local reference file found
INFO [2021-11-11 13:32:28] - => Found new reference version for hla
INFO [2021-11-11 13:32:28] - Checking KIR for IPD update...
INFO [2021-11-11 13:32:28] - => No local reference file found
INFO [2021-11-11 13:32:28] - => Found new reference version for kir
INFO [2021-11-11 13:32:39] - Retrieving new database version for hla...
DEBUG [2021-11-11 13:32:39] - 	downloading new file from https://github.com/DKMS-LSL/IMGTHLA/raw/Latest/hla.dat...
DEBUG [2021-11-11 13:34:34] - 	 => successfully downloaded new hla file
DEBUG [2021-11-11 13:34:34] - 	Getting checksum of local file E:\Novel alleles\Typeloader\_general\reference_data\temp\hla.dat...
DEBUG [2021-11-11 13:34:34] - 	=> 2ef0132f5d9bf458e9322fd8a97028c7
DEBUG [2021-11-11 13:34:34] - 		=> local MD5 checksum of downloaded file: 2ef0132f5d9bf458e9322fd8a97028c7
DEBUG [2021-11-11 13:34:34] - 	Creating parsed files...
DEBUG [2021-11-11 13:34:34] - 		Reading alleles from E:\Novel alleles\Typeloader\_general\reference_data\temp\hla.dat...
ERROR [2021-11-11 13:34:36] - Reference update failed!
Traceback (most recent call last):
  File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_functions.py", line 135, in perform_reference_update
  File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_core\update_reference.py", line 188, in update_database
  File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_core\hla_embl_parser.py", line 263, in make_parsed_files
  File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_core\hla_embl_parser.py", line 76, in read_dat_file
UnicodeDecodeError: 'cp950' codec can't decode byte 0xc2 in position 3741: illegal multibyte sequence
INFO [2021-11-11 13:35:46] - Retrieving new database version for kir...
DEBUG [2021-11-11 13:35:46] - 	downloading new file from https://github.com/DKMS-LSL/IPDKIR/raw/Latest/KIR.dat...
DEBUG [2021-11-11 13:35:59] - 	 => successfully downloaded new kir file
DEBUG [2021-11-11 13:35:59] - 	Getting checksum of local file E:\Novel alleles\Typeloader\_general\reference_data\temp\KIR.dat...
DEBUG [2021-11-11 13:35:59] - 	=> 876bbe7e0bfd9e12aea3bdf5140d612b
DEBUG [2021-11-11 13:35:59] - 		=> local MD5 checksum of downloaded file: 876bbe7e0bfd9e12aea3bdf5140d612b
DEBUG [2021-11-11 13:35:59] - 	Creating parsed files...
DEBUG [2021-11-11 13:35:59] - 		Reading alleles from E:\Novel alleles\Typeloader\_general\reference_data\temp\KIR.dat...
DEBUG [2021-11-11 13:36:00] - 			=> found 1531 alleles
DEBUG [2021-11-11 13:36:00] - 		Writing E:\Novel alleles\Typeloader\_general\reference_data\temp\parsedKIR.fa...
DEBUG [2021-11-11 13:36:00] - 		Writing E:\Novel alleles\Typeloader\_general\reference_data\temp\parsedKIR.dump...
DEBUG [2021-11-11 13:36:01] - 		Writing E:\Novel alleles\Typeloader\_general\reference_data\temp\KIR_allelenames.dump...
DEBUG [2021-11-11 13:36:01] - 		Writing E:\Novel alleles\Typeloader\_general\reference_data\temp\curr_version_KIR.txt...
DEBUG [2021-11-11 13:36:01] - 	Creating local blast database...
ERROR [2021-11-11 13:36:01] - Command '['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Novel alleles\\Typeloader\\_general\\reference_data\\temp\\parsedKIR.fa']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\schoene\WorkFolders\Code\typeloader2\typeloader2\typeloader_core\update_reference.py", line 97, in make_blast_db
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Novel alleles\\Typeloader\\_general\\reference_data\\temp\\parsedKIR.fa']' returned non-zero exit status 1.
DEBUG [2021-11-11 13:36:01] - C:\Program Files (x86)\TypeLoader\blastn\makeblastdb -dbtype nucl -in E:\Novel alleles\Typeloader\_general\reference_data\temp\parsedKIR.fa
ERROR [2021-11-11 13:36:01] - Could not create local blast database:
CalledProcessError(1, ['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Novel alleles\\Typeloader\\_general\\reference_data\\temp\\parsedKIR.fa'])
C:\Program Files (x86)\TypeLoader\blastn\makeblastdb -dbtype nucl -in E:\Novel alleles\Typeloader\_general\reference_data\temp\parsedKIR.fa
INFO [2021-11-11 13:36:01] - Tried to update the reference data for KIR to version 2.10.0, but could not process it (see below). We'll continue to use the old files for now.

Could not create local blast database:
CalledProcessError(1, ['C:\\Program Files (x86)\\TypeLoader\\blastn\\makeblastdb', '-dbtype', 'nucl', '-in', 'E:\\Novel alleles\\Typeloader\\_general\\reference_data\\temp\\parsedKIR.fa'])
C:\Program Files (x86)\TypeLoader\blastn\makeblastdb -dbtype nucl -in E:\Novel alleles\Typeloader\_general\reference_data\temp\parsedKIR.fa
INFO [2021-11-11 13:36:18] - Getting current database versions...
INFO [2021-11-11 13:36:18] - 	current HLA version is None
INFO [2021-11-11 13:36:18] - 	current KIR version is None
DEBUG [2021-11-11 13:38:13] - Opening IPD Submission dialog...
INFO [2021-11-11 13:38:13] - Opening 'IPD Submission' Dialog...
DEBUG [2021-11-11 13:38:13] - Ready for proceeding?
DEBUG [2021-11-11 13:38:13] - 	Not ready!
DEBUG [2021-11-11 13:38:13] - Ready for proceeding?
DEBUG [2021-11-11 13:38:13] - 	Not ready!
INFO [2021-11-11 13:38:13] - Reading local settings from config_local.ini...
DEBUG [2021-11-11 13:38:13] - Setting up section3 of IPDSubmissionForm...
DEBUG [2021-11-11 13:38:13] - Ready for proceeding?
DEBUG [2021-11-11 13:38:13] - 	Not ready!
DEBUG [2021-11-11 13:38:13] - Checking if IPD settings are configured...
WARNING [2021-11-11 13:38:13] - Missing IPD settings: IPD Submittor ID,Company Short Name (for IPD)


I have tried installing TypeLoader 2.11 in 2 laptops (Both Windows 10), similar error appears when creating the reference files.
Is it the problem of the blastn?
