### ISSUE TITLE
Support for novel HLA class II partial sequences

### ISSUE THREAD

**Issue by steletvinicius** [DKMS-LSL/typeloader#22]
As far as I know most clinical HLA labs running NGS are doing it using a short-reads platforms
(except for you guys from DKMS which , as far as I know from abstracts and webinars presentations, can run long reads - Nanopore sequencing. Maybe someday We will do the same in Brazil  :-)  ).
Short reads are almost always able to generate whole gene coverage and fully phased data for HLA classical and non-classical class I novel alleles. However, the challenge remains for class II genes.
As the minimun horizontal coverage demanded by IPD-IMGT/HLA database for class II genes is exon 2 region,
Could you please consider - at least for class II genes -  to improve TypeLoader so it can accept partial CDS submissions for those genes?

I am asking because that is the only reason I do not centralize all my submissions on Typeloader  and I would like to do that. : - ). Abolish Excel tables from may new allele submission protocol would help a lot.

If you need somebody to help on runnning some beta tests on this or any other new feature, You can contact me.
I would be glad to help.

**Comment by bmschoene** [comment]
I understand your pain. 
Unfortunately, expecting whole gene sequences (or at least partial versions of those covering most of the gene) is at the heart of TypeLoader. Without that, the whole "annotating your intron/exon boundaries for you" mechanism does not work, as TypeLoader wouldn't know how to find the relevant closest allele. Implementing a way to work with these would be a huge development investion, for something we don't need and are unhappy about anyway. (All those "exon 2 or 2+3 only" sequences in the reference database make whole-gene based genotyping more difficult as it creates biases in the reference.)

So I'm afraid I can't help you there. Sorry. :-(

(We actually don't do Nanopore sequencing as a standard method (at least not yet). Our high throughput genotyping is still amplicon-based using Illumina short reads. For novel alleles, we have a separate workflow that combines shotgun short reads with long reads from either PacBio or Nanopore. See https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04153-0 for the paper that explains it all.)

**Comment by bmschoene** [comment]
I mean - this is an open source project. If you can find a Python developer willing & able to put in the necessary work, let them get in touch with me and we'll see if we can work this out. But I don't think I can reasonably ask my company to pay for the development time I would need to implement this.
