### ISSUE TITLE
Typeloader unable to connect to download reference files

### ISSUE THREAD

**Issue by DavidTBrookes** [DKMS-LSL/typeloader#28]
Typeloader is unable to connect to download latest reference files on the network the Windows 10 workstation I am using is one. I am getting the following error:

![image](https://user-images.githubusercontent.com/98939295/161694081-24aedb75-fe47-4716-bb27-a6c50390a49f.png)

Could someone please help me with this issue (see below for zipped log files)?
[Typeloaderlog.zip](https://github.com/DKMS-LSL/typeloader/files/8415571/Typeloaderlog.zip)

**Comment by bmschoene** [comment]
This is the same problem as https://github.com/DKMS-LSL/typeloader/issues/27:

closing this here to keep things together.
