### ISSUE TITLE
ENA flatfile

### ISSUE THREAD

**Issue by dfuerst1** [DKMS-LSL/typeloader#36]
I created files for an ENA submission with typeloader and included 100 bases of 5' UTR 

In the exon coordinates exon 1 is listed as 1..173, but it should be 101..173 in my view CDS says join 101..173 which is correct.
Is this a bug?

FH   Key             Location/Qualifiers
FH
FT   source          1..3114
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /cell_line="ULM_23200072_A_1"
FT   CDS             join(101..173,304..573,815..1090,1691..1966,2066..2182,2621..2653,2796..2843,3013..3017)
FT                   /codon_start=1
FT                   /gene="HLA-A"
FT                   /allele="HLA-A*02:new"
FT                   /product="MHC class I antigen"
FT                   /function="antigen presenting molecule"
FT   exon            1..173
FT                   /number=1
FT                   /gene="HLA-A"
FT                   /allele="HLA-A*02:new"
FT   intron          174..303
FT                   /number=1
FT                   /gene="HLA-A"
FT                   /allele="HLA-A*02:new"

[PRJEB60375_20230309113031_flatfile.txt](https://github.com/DKMS-LSL/typeloader/files/10930499/PRJEB60375_20230309113031_flatfile.txt)

**Comment by bmschoene** [comment]
ENA counts the 5' UTR as part of exon1, and the 3' UTR as part of the last exon. So this is not a bug but the annotation format required by ENA.

In the IPD files created later, these first 100 bases will be annotated as UTR and exon 1 will start at base 101, as you expected.

Sorry for the confusion. I will include an explanation in the documentation for the future.

**Comment by bmschoene** [comment]
(You will see the same phenomenon when you look at the ENA- and IPD files created from the provided example sequences.)
