### ISSUE TITLE
config_raw.ini missing on Linux

### ISSUE THREAD

**Issue by irunonayran** [DKMS-LSL/typeloader#46]
Following the setup_linux.md, I get errors that the config files are missing. `cd typeloader2; poetry run python typeloader_GUI.py`
instead of `poetry run python typeloader2/typeloader_GUI.py` seems to do the job.

**Comment by bmschoene** [comment]
Thank you! I'll fix that in the documentation.
We haven't had any Linux users to try this, yet, so I'm very grateful for the input!
