### ISSUE TITLE
ENA submission error: system error and read timed out

### ISSUE THREAD

**Issue by kashastrickland** [DKMS-LSL/typeloader#48]
Hello. 

Really hoping someone can help here as I am currently trying to upload sequence data (for about N = 350 samples) to ENA via the webin-cli.jar command line application, but I am no longer able to connect to the server (seemingly).

I set up everything to upload all reads about 5 days and successfully uploaded around half of those before the system seemed to completely break. Now, I am unable to get anything to start uploading - and it looks to me that I am not able to connect to ENA's server.

This is the command I am running:

**java -jar webin-cli-8.0.0.jar -context=reads -manifest=manifest.txt -username=*** -password=*** -inputdir ./ -submit**

which gives the following errors:

**WARN : Retrying working directory change on FTP server.
INFO : Connecting to FTP server : webin2.ebi.ac.uk
ERROR: Failed to upload files to FTP server. Failed to upload files to server because of a system error.
ERROR: Some or all submissions failed. Please see application logs.**

I am not pasting the full log of this - but this seems to be the most relevant info:

**Caused by: java.net.SocketTimeoutException: Read timed out**

which suggested to me that I am not able to connect to ENAs server in order to upload my data. 

I have tried to use a few different versions of the webin-cli plugin (8.0.0m 7.3.1 and older) - all of which give the same issue. Also, following some advice from older posts (this seems to be a really common problem using this tool) I tried using and adding in "-ascp" to the command + removing all previous log files to ensure it's not a re-writable problem.

Can anyone help and/or advise what might be going on here? They have updated the version since I started this to 8.0.0 and I needed to update java - which all looked to be fine - but the problem is happening irrespective of the version I am using. My code worked fine so it can't be that - and therefore assuming its a connectivity issue, but need to get these uploaded ASAP so would be good to know why it's crashed. 

Thanks in advance for any help!

**Comment by kashastrickland** [comment]
Sorry for confusion - have just found out it's because ENA is unavailable until tomorrow. Will try again then

**Comment by bmschoene** [comment]
Yes. They announced the downtime would possibly last until tomorrow, so it's probably wisest to try again next week.
