### ISSUE TITLE
problem adding an allele

### ISSUE THREAD

**Issue by droe-nmdp** [DKMS-LSL/typeloader#6]
[C_test.txt](https://github.com/DKMS-LSL/typeloader/files/2776948/C_test.txt)
I'm testing the ability to add an allele (attached -- had to rename form fasta to txt to upload).
I choose that file from the dialog box.
I create a new project with gene 'HLA-C' and pool 'test'. I click 'Load' and enter 'test' for the internal and external IDs.

I then get a dialog box titled 'Error while processing the sequence file'. The text of the box is "FileNotFoundError(2,'No such file or directory')".

Any suggestions? I'm not doing anything with ENA, I just want to test the allele annotation for now.

**Comment by droe-nmdp** [comment]
I tried using this[1] sequence (also attached and added a '.txt' extension for upload to github) and got the same message. Should that file work? If not, would you send me a file I can use for a test?

1. https://www.ncbi.nlm.nih.gov/nuccore/LS992452.1

[C_dkms.fasta.txt](https://github.com/DKMS-LSL/typeloader/files/2963594/C_dkms.fasta.txt)

**Comment by bmschoene** [comment]
@droe-nmdp Oops, this is a bug. Will fix this in the next release.
Until then, change the file extension to .fa instead of .fasta and it should work (it does here). Please let me know how it turns out?

(The allele you have found has meanwhile been named, so in the end, this will create a confirmatory file for IPD. If you want to test what novel allele files look like, just change some of the bases in the sequence.)

**Comment by droe-nmdp** [comment]
I use the file extension of .fasta. I only renamed the file to .txt because Github doesn't allow me to upload files with a .fasta extension.

Can you recreate the issue using the .fasta extension?

**Comment by bmschoene** [comment]
Yes, if I use the file extension .fasta I get the same problem. That's the bug I meant. (I have a good idea what the problem is, and will fix that in the next release.)

But if I rename the file from .fasta to .fa, it works for me. Does that work for you, too?

**Comment by droe-nmdp** [comment]
Yes, I confirm that it works with the .fa extension. I apologize for my misunderstanding.

Thank you!

**Comment by bmschoene** [comment]
Great, problem solved! :-)
I'm looking forward to your feedback once you get some experience with TypeLoader. :-)
