### ISSUE TITLE
can't download example files

### ISSUE THREAD

**Issue by droe-nmdp** [DKMS-LSL/typeloader#7]
Operation: Options -> Download example files, then click on 'Pretypings File'. Select the
destination and click 'Save'.
Result: the app crashes and the file(s) are not saved. I have to restart the app to continue.

I'm running 2.0.0 on Windows 10.

**Comment by bmschoene** [comment]
(I'm presuming you mean 2.1.0, as the example files were not present in 2.0.0.?)

This is weird. Can you please attach your latest log file (or the relevant part)? You should find it in the path you provided as TypeLoader's data path => recovery => the .log file with the timestamp of when you started the app. (If in doubt, restart TypeLoader, then perform the steps again. Then send the latest log file.)
(You will probably have to rename to .txt for GitHub, again.)

**Comment by droe-nmdp** [comment]
[20190315_132310.log](https://github.com/DKMS-LSL/typeloader/files/2972451/20190315_132310.log)

Yes, version 2.2.0. Based on the log, I looked for a folder called 'sample_files' and didn't find one.

**Comment by bmschoene** [comment]
Hm. The directory "sample_files" should be in the src directory where the TypeLoader code is. 
It is in the GitHub repo, so I don't know why it isn't in yours?

For now, I'm attaching it here:
[pretypings_example.csv.txt](https://github.com/DKMS-LSL/typeloader/files/2976999/pretypings_example.csv.txt) (remove the .txt extension)

Will make extra sure to test this once the next installer is built. (That will also contain sample files for each step.)

**Comment by droe-nmdp** [comment]
Thank you.

I suggested adding more files to the sample files. For example, I think people may like to see the output from the two submission steps (e.g., the ena.txt files).

**Comment by bmschoene** [comment]
I agree. This is already planned for the next release. (I plan to include at least one working sample input file per gene system (HLA, KIR, MIC), as well as a corresponding ENA-reply file and a corresponding pretypings file. This way, users can test the whole workflow using these files, and see the generated output.)

**Comment by droe-nmdp** [comment]
Thank you.
