### ISSUE TITLE
can't find the right starting point for 2DL1 allele

### ISSUE THREAD

**Issue by droe-nmdp** [DKMS-LSL/typeloader#8]
I'm trying to add a KIR2DL1 allele. When I load 2DL1_test_smaller.fa, it fails with "This sequence misses the first 2675 bp!". When I add 3000bp to the beginning (2DL1_test_middle.fa), it fails with "This sequence misses the first 15433 bp!".

How precise a window do the start and end locations need to be? Can you give me a version of this allele (or another 2DL1 allele) that is the right size in the right location?

[2DL1_test_smaller.fa.txt](https://github.com/DKMS-LSL/typeloader/files/2968145/2DL1_test_smaller.fa.txt)

[2DL1_test_middle.fa.txt](https://github.com/DKMS-LSL/typeloader/files/2968137/2DL1_test_middle.fa.txt)

**Comment by droe-nmdp** [comment]
The same (missing > 15k) from this 2DL4 file.


[2DL4_test1.fa.txt](https://github.com/DKMS-LSL/typeloader/files/2968187/2DL4_test1.fa.txt)

**Comment by bmschoene** [comment]
The fasta sequence you upload should align to the official reference sequences, starting at the beginning of the official UTR for the gene, and ending at the end of the official UTR for the gene, and covering everything in between in one sequence.
I don't think your current sequences do that? (I've tried aligning them to a reference full-length 2DL4 allele and they look way off. Which is probably why TypeLoader is giving you those confusing numbers. TypeLoader is based on the assumption that the sequence it gets is exactly the sequence that you want to submit to IPD. It doesn't cut, it just does the annotation for you.)

Here's an example file for an existing allele: [KIR2DL4_0010201.fa.txt](https://github.com/DKMS-LSL/typeloader/files/2970024/KIR2DL4_0010201.fa.txt)

However, the next release is planned to allow for incomplete UTRs, too, so you will then only need to have at least one bp of each UTR (which is the minimum requirement of IPD for genomic sequences). You should still not have anything in your fasta that doesn't belong to the allele you want to submit.

**Comment by droe-nmdp** [comment]
Thank you.
