### ISSUE TITLE
question about UTRs and first/last exons

### ISSUE THREAD

**Issue by droe-nmdp** [DKMS-LSL/typeloader#9]
The intron/exon annotation for both HLA and KIR combines the UTRs with the first/last exons. I'm curious about that choice instead of separating the UTRs from the exons. Is that the way IMGT/IPD wants them annotated, for example?

**Comment by bmschoene** [comment]
This is how ENA wants the annotations. The actual boundaries of the first and last exon is encoded in the CDS positions, though.

In the files for IPD (which are created during the 'IPD submission' step), the UTRs get their own annotations.

**Comment by droe-nmdp** [comment]
Thank you.
